# Generated by Django 4.2.7 on 2026-05-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='related_reports',
            field=models.ManyToManyField(blank=True, related_name='related_to', to='reports.report'),
        ),
    ]
